### ISSUE TITLE
Initializer lists fail on nested structs

### ISSUE THREAD

**Issue by InterplanetaryEngineer** [Vexu/arocc#233] opened 2022-02-04 22:08 UTC
```c
struct MyStruct {
  int b;
};

struct A {
  struct MyStruct d;
};

struct A f() {
  struct MyStruct e;
  return (struct A){.d = e};
}
```
unexpectedly fails with:
```
test.c:11:19: error: initializing 'int' from incompatible type 'struct MyStruct'
  return (struct A){.d = e};
                  ^
```

**Comment by Vexu** [comment] 2022-02-04 22:16
Duplicate of  #189

**Closed by Vexu** 2022-02-04 22:16 UTC

**Comment by InterplanetaryEngineer** [comment] 2022-02-04 22:31
Oops. Thanks!
